apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    app: e-commerce
    tier: services
  namespace: dicoding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commerce
      tier: services
  template:
    metadata:
      labels:
        app: e-commerce
        tier: services
    spec:
      containers:
        - name: shipping
          image: ghcr.io/pyroblazer/shipping-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-rabbitmq
                  key: rabbitmq-password
            - name: AMQP_URL
              value: "amqp://user:$(AMQP_PASSWORD)@my-rabbitmq:5672"