apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: dicoding
  labels:
    app: e-commerce
    tier: services
spec:
  selector:
    app: e-commerce
    tier: services
  ports:
    - name: default
      port: 3001
      protocol: TCP