apiVersion: apps/v1
kind: Deployment
metadata:
  name: order  # Unique name for this deployment
  namespace: dicoding  # Namespace for organizational purposes
  labels:
    app: e-commerce  # Application label for grouping resources
    tier: services   # Tier label indicating the service level
spec:
  replicas: 1  # Number of desired replicas for the deployment
  selector:
    matchLabels:
      app: e-commerce  # Select pods with this app label
      tier: services   # Select pods with this tier label
  template:
    metadata:
      labels:
        app: e-commerce  # Labels for the pods created by this template
        tier: services   
    spec:
      containers:
        - name: order  # Container name for identifying the pod
          image: ghcr.io/pyroblazer/order-service:latest  # Docker image for the container
          ports:
            - containerPort: 3000  # Port on which the container will listen
          env:
            - name: PORT
              value: "3000"  # Port value for the application
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-rabbitmq  # Secret name for AMQP credentials
                  key: rabbitmq-password  # Key within the secret for AMQP password
            - name: AMQP_URL
              value: "amqp://user:$(AMQP_PASSWORD)@my-rabbitmq:5672"
              # Connection URL using the AMQP password from the secret