apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: dicoding
  labels:
    app: e-commerce
    tier: services
spec:
  ports:
    - name: default
      port: 3000
      protocol: TCP
  selector:
    app: e-commerce
    tier: services