apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: order
  namespace: dicoding
spec:
  hosts:
    - "*"
  gateways:
    - order-gateway
  http:
    - match:
        - uri:
            exact: "/order"
      route:
        - destination:
            host: order
            port:
              number: 3000